import type { Metadata } from "next";
import Image from "next/image";
import { Footer } from "@/components/layout/Footer";
import { withBasePath } from "@/lib/constants";

export const metadata: Metadata = { title: "About", description: "About Osama Kolachi—creative developer, systems thinker and interaction designer in Dubai." };
const experience = [["2024—Now", "Independent", "Creative Developer"], ["2022—24", "Digital Product Studio", "Lead Engineer"], ["2019—22", "Technology & Design", "Frontend Developer"]];

export default function AboutPage() { return <main className="page-shell"><header className="page-hero"><div className="page-kicker eyebrow"><span>About / Profile</span><span>Dubai — UAE</span></div><h1 className="display">Logic <span className="serif">with</span><br />feeling.</h1></header><section className="section about-statement"><div className="portrait"><Image src={withBasePath("/images/portraits/osama-about.png")} alt="Portrait of Osama Kolachi" width={1033} height={1522} /></div><div><p className="editorial-copy">I turn complex ideas into digital experiences people can feel, use and remember.</p><p style={{ maxWidth: "32rem", marginTop: "4rem", lineHeight: 1.6, color: "var(--muted)" }}>My practice moves between design and engineering. I work with ambitious teams to shape the system, the interface and the small details that make an experience unmistakably itself.</p></div></section><section className="section"><div className="about-index"><h2>01 / Philosophy</h2><p className="large">Technology should disappear into the experience. The work stays expressive, but every gesture earns its place.</p></div><div className="about-index"><h2>02 / Experience</h2><div>{experience.map((item) => <div className="timeline-item" key={item[0]}><span>{item[0]}</span><strong>{item[1]}</strong><span>{item[2]}</span></div>)}</div></div><div className="about-index"><h2>03 / Capabilities</h2><p className="large">Creative development / AI systems / interaction design / WebGL / product engineering / technical direction</p></div><div className="about-index"><h2>04 / Tools</h2><p className="large">TypeScript, React, Next.js, Three.js, GLSL, GSAP, design systems and whatever the idea genuinely needs.</p></div><div className="about-index"><h2>05 / Currently exploring</h2><p className="large">Interfaces with memory, useful machine intelligence and digital objects that behave more like material than media.</p></div></section><Footer /></main>; }
